---
title: "Homework 5"
author: "Madison Johnson"
date: "2025-12-01"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
library(scales)
```

```{r loading, message=FALSE}
file_path <- "data/homicide-data.csv"
homicide_data <- read_csv(file_path)
```

```{r baltimore}
homicides <- homicide_data %>% 
  unite(col = "city_name", c("city", "state"), sep = ", ")

baltimore <- homicides %>% 
   filter(city_name == "Baltimore, MD")

head(baltimore)
```

```{r cleanup}
baltimore <- baltimore %>% 
  mutate("reported_date" = ymd(reported_date)) %>% 
  rename("date" = reported_date)

balt_month <- baltimore %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(year, month) %>% 
  summarise(n = n()) %>% 
  ungroup

balt_month2 <- balt_month %>% 
  unite("yr_month", year, month, sep = "-") %>% 
  mutate("yr_month" = ymd(paste0(yr_month, "-01"))) %>% 
  mutate("month" = factor(format(yr_month, "%m"))) %>% 
 mutate(season = ifelse(as.numeric(month) %in% c(11, 12, 1, 2, 3, 4), "Winter", "Summer"))
```

```{r plotting}
balt_month2 %>% 
  ggplot(aes(x = yr_month, y = n, fill = season)) +
  geom_col() +
  labs(title = "Homicides in Baltimore, MD",
       x = "Date",
       y = "Monthly Homicides") +
  scale_fill_manual(values = c("Winter" = "lightblue",
                               "Summer" = "lightgray")) +
  geom_vline(xintercept = as.Date("2015-04-01"),
             color = "red",
             linetype = "dashed") +
  annotate("text", x = as.Date("2013-04-01"),
           y = 43,
           label = "Arrest of",
           color = "lightgray") +
  annotate("text", x = as.Date("2013-04-01"),
           y = 37,
           label = "Freddie Gray",
           color = "lightgray") +
  theme_dark()
```

